# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-10 10:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0002_auto_20190816_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='正文'),
        ),
    ]
